// Generated canonical doctrine & SOP corpus dataset for fail-soft offline access.
// Mirrors the 15 canonical Markdown files in corpus/ (POL-01..03, REF-01..04, SOP-01..08).
import type { CorpusDocDetail } from "@/lib/api";

export const BUNDLED_CORPUS_DOCS: CorpusDocDetail[] = [
  {
    id: "POL-01",
    category: "POL",
    title: "Rules of Engagement (Simulated)",
    tags: ["roe", "policy", "engagement", "guardrails"],
    version: "1.0",
    content:
      "# POL-01 \u2014 Rules of Engagement (Simulated)\n\n_Simulated training policy for exercise play only. Not real ROE. This platform contains no engagement mechanics._\n\n## 1. Scope\n\nThese rules govern how simulated units respond to contacts and threats within DOIP exercises. The platform simulates **defensive and support operations only**; offensive strike planning is outside scope by design and cannot be scripted.\n\n## 2. Standing rules\n\n1. Observation and reporting are always authorized (SOP-01).\n2. Units hold position and observe on contact; they do not pursue.\n3. Defensive posture changes (SOP-07 Green/Amber/Red) require operator decision, logged with reason.\n4. Escalation beyond posture change \u2014 QRF deployment, airspace closure recommendation, sector lockdown \u2014 requires the role authority defined in REF-04.\n5. No simulated unit acts autonomously against a contact: every response is a human decision, recorded as a decision event.\n\n## 3. Air tracks\n\nCounter-UAS responses follow SOP-05's response ladder and stop at tracking, alerting, and defensive posture. Engagement is not simulated.\n\n## 4. Exercise conduct\n\nRed-Team injects must comply with the fairness constraints in the inject playbook and are always disclosed in the after-action report. Attempting to script actions outside the DSL whitelist is a validation error, not a gray area.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "POL-01 \u2014 Rules of Engagement (Simulated)",
        text: "_Simulated training policy for exercise play only. Not real ROE. This platform contains no engagement mechanics._",
      },
      {
        heading: "1. Scope",
        text: "These rules govern how simulated units respond to contacts and threats within DOIP exercises. The platform simulates **defensive and support operations only**; offensive strike planning is outside scope by design and cannot be scripted.",
      },
      {
        heading: "2. Standing rules",
        text: "1. Observation and reporting are always authorized (SOP-01).\n2. Units hold position and observe on contact; they do not pursue.\n3. Defensive posture changes (SOP-07 Green/Amber/Red) require operator decision, logged with reason.\n4. Escalation beyond posture change \u2014 QRF deployment, airspace closure recommendation, sector lockdown \u2014 requires the role authority defined in REF-04.\n5. No simulated unit acts autonomously against a contact: every response is a human decision, recorded as a decision event.",
      },
      {
        heading: "3. Air tracks",
        text: "Counter-UAS responses follow SOP-05's response ladder and stop at tracking, alerting, and defensive posture. Engagement is not simulated.",
      },
      {
        heading: "4. Exercise conduct",
        text: "Red-Team injects must comply with the fairness constraints in the inject playbook and are always disclosed in the after-action report. Attempting to script actions outside the DSL whitelist is a validation error, not a gray area.",
      },
    ],
  },
  {
    id: "POL-02",
    category: "POL",
    title: "Data Handling Policy",
    tags: ["data", "policy", "synthetic", "privacy"],
    version: "1.0",
    content:
      "# POL-02 \u2014 Data Handling Policy\n\n_Simulated training policy._\n\n## 1. Synthetic-only rule\n\nAll operational data in DOIP is synthetic, generated by the simulation engine or authored as exercise content. It is prohibited to load real operational data \u2014 real unit positions, real personnel records, real sensor feeds, or classified material of any kind \u2014 into any DOIP environment. There is no approved exception path; a system that never contains real data cannot leak it.\n\n## 2. Personnel data\n\nSimulated personnel (names, vitals, rosters) are generated fictions. Real user accounts hold only: username, role, and authentication credentials. User activity (decisions, acknowledgments, annotations) is logged for training review \u2014 participants must be informed that exercise performance is recorded and replayable.\n\n## 3. Retention and replay\n\nEvent logs are append-only and retained for the training program's review period. Runs may be deleted only whole (run-level purge by an admin, itself an audited action) \u2014 selective event deletion is prohibited because it breaks replay integrity.\n\n## 4. Exports\n\nAfter-action reports and analytics exports inherit this policy: synthetic content, role names rather than personal blame framing (POL-03), and the standing disclaimer \u2014 _\u201cTraining & simulation platform. All data is synthetic. Not for operational military use.\u201d_",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "POL-02 \u2014 Data Handling Policy",
        text: "_Simulated training policy._",
      },
      {
        heading: "1. Synthetic-only rule",
        text: "All operational data in DOIP is synthetic, generated by the simulation engine or authored as exercise content. It is prohibited to load real operational data \u2014 real unit positions, real personnel records, real sensor feeds, or classified material of any kind \u2014 into any DOIP environment. There is no approved exception path; a system that never contains real data cannot leak it.",
      },
      {
        heading: "2. Personnel data",
        text: "Simulated personnel (names, vitals, rosters) are generated fictions. Real user accounts hold only: username, role, and authentication credentials. User activity (decisions, acknowledgments, annotations) is logged for training review \u2014 participants must be informed that exercise performance is recorded and replayable.",
      },
      {
        heading: "3. Retention and replay",
        text: "Event logs are append-only and retained for the training program's review period. Runs may be deleted only whole (run-level purge by an admin, itself an audited action) \u2014 selective event deletion is prohibited because it breaks replay integrity.",
      },
      {
        heading: "4. Exports",
        text: "After-action reports and analytics exports inherit this policy: synthetic content, role names rather than personal blame framing (POL-03), and the standing disclaimer \u2014 _\u201cTraining & simulation platform. All data is synthetic. Not for operational military use.\u201d_",
      },
    ],
  },
  {
    id: "POL-03",
    category: "POL",
    title: "After-Action Report Template",
    tags: ["aar", "template", "debrief", "review"],
    version: "1.0",
    content:
      "# POL-03 \u2014 After-Action Report Template\n\n_Simulated training policy. This template is the required structure for every exercise AAR; the aar-summarizer prompt follows it verbatim._\n\n## Required sections\n\n1. **Summary** \u2014 scenario, seed, duration, participating roles, end condition reached. Three to five sentences.\n2. **Timeline highlights** \u2014 chronological key events with event citations `[e:<id>]`: contacts, alerts, dispatches, casualties, posture changes, injects.\n3. **Decision review** \u2014 each significant decision: what was decided, by which role, at what sim-time, what followed. Name roles, not individuals. No blame language; the AAR evaluates process, not people.\n4. **Metrics** \u2014 the primary KPIs, verbatim from analytics: time-to-acknowledge (high/critical), QRF time-on-scene vs the 20-minute standard, urgent CASEVAC vs the 60-minute standard, comms-loss minutes, resource-empty incidents.\n5. **Red-Team disclosure** \u2014 every inject with timing and rationale. Mandatory when injects occurred; write \u201cNo injects\u201d otherwise.\n6. **Lessons observed** \u2014 two to five, each traceable to cited evidence. \u201cObserved\u201d, not \u201clearned\u201d: a lesson is learned only when a later run shows the change.\n\n## Rules\n\n- Every claim in sections 2\u20133 carries an event citation; uncited claims are removed at review.\n- The AAR is distributed to all participants \u2014 write it to be read by the people it evaluates.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "POL-03 \u2014 After-Action Report Template",
        text: "_Simulated training policy. This template is the required structure for every exercise AAR; the aar-summarizer prompt follows it verbatim._",
      },
      {
        heading: "Required sections",
        text: "1. **Summary** \u2014 scenario, seed, duration, participating roles, end condition reached. Three to five sentences.\n2. **Timeline highlights** \u2014 chronological key events with event citations `[e:<id>]`: contacts, alerts, dispatches, casualties, posture changes, injects.\n3. **Decision review** \u2014 each significant decision: what was decided, by which role, at what sim-time, what followed. Name roles, not individuals. No blame language; the AAR evaluates process, not people.\n4. **Metrics** \u2014 the primary KPIs, verbatim from analytics: time-to-acknowledge (high/critical), QRF time-on-scene vs the 20-minute standard, urgent CASEVAC vs the 60-minute standard, comms-loss minutes, resource-empty incidents.\n5. **Red-Team disclosure** \u2014 every inject with timing and rationale. Mandatory when injects occurred; write \u201cNo injects\u201d otherwise.\n6. **Lessons observed** \u2014 two to five, each traceable to cited evidence. \u201cObserved\u201d, not \u201clearned\u201d: a lesson is learned only when a later run shows the change.",
      },
      {
        heading: "Rules",
        text: "- Every claim in sections 2\u20133 carries an event citation; uncited claims are removed at review.\n- The AAR is distributed to all participants \u2014 write it to be read by the people it evaluates.",
      },
    ],
  },
  {
    id: "REF-01",
    category: "REF",
    title: "Unit Type Capabilities Sheet",
    tags: ["units", "capabilities", "reference"],
    version: "1.0",
    content:
      "# REF-01 \u2014 Unit Type Capabilities Sheet\n\n_Simulated training reference. Values are exercise parameters, not real specifications._\n\n| Unit type                  | Personnel           | Speed (std)                   | Endurance            | Carries                          | Notes                             |\n| -------------------------- | ------------------- | ----------------------------- | -------------------- | -------------------------------- | --------------------------------- |\n| Ground patrol team         | 4\u20136                 | 5 km/h foot / 40 km/h vehicle | 8 sim-hours          | medkit, radio                    | Standard patrol & perimeter unit  |\n| QRF element                | 8\u201312                | 60 km/h                       | 6 sim-hours          | medkit \u00d72, breach kit            | SOP-02 response standards apply   |\n| Recon UAV                  | 0 (operator remote) | 70 km/h                       | 90 sim-min / battery | EO camera                        | Grounded in storm intensity \u2265 0.6 |\n| Cargo/convoy vehicle       | 2                   | 50 km/h (convoy: slowest)     | fuel-limited         | 2,000 kg supplies                | SOP-04 spacing rules              |\n| Medical evacuation vehicle | 3                   | 55 km/h                       | fuel-limited         | 2 litters, med station           | SOP-03 precedence rules           |\n| Supply depot (static)      | 6                   | \u2014                             | \u2014                    | fuel, medkit, rations, batteries | Resupply threshold 30% (50% HADR) |\n\n## Usage notes\n\n- Speeds are modified by weather multipliers and terrain cost layers; the values above are clear-condition standards.\n- Battery-powered assets report remaining percentage every position report; below 25% they must plan return-to-base.\n- Personnel counts drive vitals simulation and CASEVAC capacity checks.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "REF-01 \u2014 Unit Type Capabilities Sheet",
        text: "_Simulated training reference. Values are exercise parameters, not real specifications._\n\n| Unit type                  | Personnel           | Speed (std)                   | Endurance            | Carries                          | Notes                             |\n| -------------------------- | ------------------- | ----------------------------- | -------------------- | -------------------------------- | --------------------------------- |\n| Ground patrol team         | 4\u20136                 | 5 km/h foot / 40 km/h vehicle | 8 sim-hours          | medkit, radio                    | Standard patrol & perimeter unit  |\n| QRF element                | 8\u201312                | 60 km/h                       | 6 sim-hours          | medkit \u00d72, breach kit            | SOP-02 response standards apply   |\n| Recon UAV                  | 0 (operator remote) | 70 km/h                       | 90 sim-min / battery | EO camera                        | Grounded in storm intensity \u2265 0.6 |\n| Cargo/convoy vehicle       | 2                   | 50 km/h (convoy: slowest)     | fuel-limited         | 2,000 kg supplies                | SOP-04 spacing rules              |\n| Medical evacuation vehicle | 3                   | 55 km/h                       | fuel-limited         | 2 litters, med station           | SOP-03 precedence rules           |\n| Supply depot (static)      | 6                   | \u2014                             | \u2014                    | fuel, medkit, rations, batteries | Resupply threshold 30% (50% HADR) |",
      },
      {
        heading: "Usage notes",
        text: "- Speeds are modified by weather multipliers and terrain cost layers; the values above are clear-condition standards.\n- Battery-powered assets report remaining percentage every position report; below 25% they must plan return-to-base.\n- Personnel counts drive vitals simulation and CASEVAC capacity checks.",
      },
    ],
  },
  {
    id: "REF-02",
    category: "REF",
    title: "Severity Classification Guide",
    tags: ["severity", "classification", "alerts", "triage"],
    version: "1.0",
    content:
      "# REF-02 \u2014 Severity Classification Guide\n\n_Simulated training reference._\n\n## Severity levels\n\n| Level        | Definition                  | UI treatment                                 | Examples                                                                                        |\n| ------------ | --------------------------- | -------------------------------------------- | ----------------------------------------------------------------------------------------------- |\n| **Low**      | Routine, informational      | feed + ticker only                           | position report, scheduled resupply                                                             |\n| **Medium**   | Deviation needing awareness | feed + map badge                             | stage-2 comms loss, weather cell entering sector, stock below 40%                               |\n| **High**     | Requires operator action    | toast + badge + map ping                     | contact report (initial), confirmed perimeter event, stock below 30%, stage-3 comms loss        |\n| **Critical** | Immediate command attention | toast + commander notify + persistent banner | casualty with critical vitals, hostile-behavior air track, confirmed breach, stage-4 comms loss |\n\n## Classification rules\n\n1. Initial classification is automatic per the event-type mappings above; operators may upgrade freely but may downgrade only with a logged reason.\n2. Contact reports never enter below **high** (SOP-01 \u00a73).\n3. Two related medium events in the same sector within 10 sim-minutes auto-escalate to high.\n4. Acknowledgment is required for high and critical; time-to-acknowledge is a primary exercise KPI.\n\n## Medical vitals bands\n\n| Band     | Heart rate             | Fatigue index | Action                            |\n| -------- | ---------------------- | ------------- | --------------------------------- |\n| Normal   | 60\u2013100                 | < 0.6         | none                              |\n| Degraded | 100\u2013130                | 0.6\u20130.8       | medium alert, rotation suggested  |\n| Critical | > 130 sustained 10 min | > 0.8         | critical alert, SOP-03 assessment |",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "REF-02 \u2014 Severity Classification Guide",
        text: "_Simulated training reference._",
      },
      {
        heading: "Severity levels",
        text: "| Level        | Definition                  | UI treatment                                 | Examples                                                                                        |\n| ------------ | --------------------------- | -------------------------------------------- | ----------------------------------------------------------------------------------------------- |\n| **Low**      | Routine, informational      | feed + ticker only                           | position report, scheduled resupply                                                             |\n| **Medium**   | Deviation needing awareness | feed + map badge                             | stage-2 comms loss, weather cell entering sector, stock below 40%                               |\n| **High**     | Requires operator action    | toast + badge + map ping                     | contact report (initial), confirmed perimeter event, stock below 30%, stage-3 comms loss        |\n| **Critical** | Immediate command attention | toast + commander notify + persistent banner | casualty with critical vitals, hostile-behavior air track, confirmed breach, stage-4 comms loss |",
      },
      {
        heading: "Classification rules",
        text: "1. Initial classification is automatic per the event-type mappings above; operators may upgrade freely but may downgrade only with a logged reason.\n2. Contact reports never enter below **high** (SOP-01 \u00a73).\n3. Two related medium events in the same sector within 10 sim-minutes auto-escalate to high.\n4. Acknowledgment is required for high and critical; time-to-acknowledge is a primary exercise KPI.",
      },
      {
        heading: "Medical vitals bands",
        text: "| Band     | Heart rate             | Fatigue index | Action                            |\n| -------- | ---------------------- | ------------- | --------------------------------- |\n| Normal   | 60\u2013100                 | < 0.6         | none                              |\n| Degraded | 100\u2013130                | 0.6\u20130.8       | medium alert, rotation suggested  |\n| Critical | > 130 sustained 10 min | > 0.8         | critical alert, SOP-03 assessment |",
      },
    ],
  },
  {
    id: "REF-03",
    category: "REF",
    title: "Sector Map Legend & Zone Types",
    tags: ["map", "sectors", "zones", "legend"],
    version: "1.0",
    content:
      "# REF-03 \u2014 Sector Map Legend & Zone Types\n\n_Simulated training reference._\n\n## Sectors\n\nThe operational area is divided into lettered sectors (A, B, C, \u2026) defined in each scenario's GeoJSON. Sector boundaries drive War-Room operator scoping, alert routing, and analytics grouping.\n\n## Zone types\n\n| Zone            | Map style                  | Meaning                                     | Routing behavior          |\n| --------------- | -------------------------- | ------------------------------------------- | ------------------------- |\n| Patrol zone     | dashed blue outline        | Assigned patrol area                        | preferred cost            |\n| Monitoring zone | dotted amber outline       | Watch area; unknown tracks raise medium     | normal cost               |\n| Restricted zone | solid red fill (hatched)   | No entry without authorization              | never routed through      |\n| Threat zone     | orange gradient fill       | Elevated risk (scenario- or inject-defined) | high routing cost         |\n| Weather cell    | translucent gray/blue blob | Active weather; slows units                 | dynamic cost by intensity |\n\n## Marker severity shapes\n\nIncidents render by severity: \u25cf low \u00b7 \u25a0 medium \u00b7 \u25b3 high \u00b7 \u25c8 critical. Stale unit markers (missed report window) show a hollow outline with last-report age.\n\n## Attribution\n\nBase map: \u00a9 OpenStreetMap contributors (ODbL) \u2014 the attribution line is mandatory on every map view, including screenshots in reports.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "REF-03 \u2014 Sector Map Legend & Zone Types",
        text: "_Simulated training reference._",
      },
      {
        heading: "Sectors",
        text: "The operational area is divided into lettered sectors (A, B, C, \u2026) defined in each scenario's GeoJSON. Sector boundaries drive War-Room operator scoping, alert routing, and analytics grouping.",
      },
      {
        heading: "Zone types",
        text: "| Zone            | Map style                  | Meaning                                     | Routing behavior          |\n| --------------- | -------------------------- | ------------------------------------------- | ------------------------- |\n| Patrol zone     | dashed blue outline        | Assigned patrol area                        | preferred cost            |\n| Monitoring zone | dotted amber outline       | Watch area; unknown tracks raise medium     | normal cost               |\n| Restricted zone | solid red fill (hatched)   | No entry without authorization              | never routed through      |\n| Threat zone     | orange gradient fill       | Elevated risk (scenario- or inject-defined) | high routing cost         |\n| Weather cell    | translucent gray/blue blob | Active weather; slows units                 | dynamic cost by intensity |",
      },
      {
        heading: "Marker severity shapes",
        text: "Incidents render by severity: \u25cf low \u00b7 \u25a0 medium \u00b7 \u25b3 high \u00b7 \u25c8 critical. Stale unit markers (missed report window) show a hollow outline with last-report age.",
      },
      {
        heading: "Attribution",
        text: "Base map: \u00a9 OpenStreetMap contributors (ODbL) \u2014 the attribution line is mandatory on every map view, including screenshots in reports.",
      },
    ],
  },
  {
    id: "REF-04",
    category: "REF",
    title: "Escalation Matrix",
    tags: ["escalation", "roles", "notification", "matrix"],
    version: "1.0",
    content:
      "# REF-04 \u2014 Escalation Matrix\n\n_Simulated training reference._\n\n## Who is notified, when\n\n| Trigger                    | Operator              | Planner  | Commander               | Action reference      |\n| -------------------------- | --------------------- | -------- | ----------------------- | --------------------- |\n| Medium alert               | feed/badge            | \u2014        | \u2014                       | monitor               |\n| High alert                 | notify + ack required | \u2014        | \u2014                       | SOP per event type    |\n| Critical alert             | notify + ack required | notified | notify + banner         | immediate             |\n| Stage-3 comms loss         | ack required          | \u2014        | \u2014                       | SOP-06, QRF readiness |\n| Stage-4 comms loss         | ack required          | notified | notified                | SOP-06 search plan    |\n| Confirmed perimeter event  | ack required          | \u2014        | posture Amber+ notified | SOP-07                |\n| Convoy > 45 min late       | ack required          | notified | \u2014                       | SOP-04 \u00a75             |\n| Urgent CASEVAC             | ack required          | \u2014        | notified                | SOP-03                |\n| Hostile-behavior air track | ack required          | notified | notify + banner         | SOP-05                |\n\n## Alternate designation\n\nIf a primary responder (e.g., QRF) fails feasibility checks, the alternate is the nearest same-type unit with passing checks; ties break by lowest callsign. The designation is a logged operator decision.\n\n## Time standards\n\nAcknowledgment: 2 sim-minutes (high), 1 sim-minute (critical). Unacknowledged critical alerts re-notify every 2 sim-minutes and appear in the after-action report with total unacknowledged time.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "REF-04 \u2014 Escalation Matrix",
        text: "_Simulated training reference._",
      },
      {
        heading: "Who is notified, when",
        text: "| Trigger                    | Operator              | Planner  | Commander               | Action reference      |\n| -------------------------- | --------------------- | -------- | ----------------------- | --------------------- |\n| Medium alert               | feed/badge            | \u2014        | \u2014                       | monitor               |\n| High alert                 | notify + ack required | \u2014        | \u2014                       | SOP per event type    |\n| Critical alert             | notify + ack required | notified | notify + banner         | immediate             |\n| Stage-3 comms loss         | ack required          | \u2014        | \u2014                       | SOP-06, QRF readiness |\n| Stage-4 comms loss         | ack required          | notified | notified                | SOP-06 search plan    |\n| Confirmed perimeter event  | ack required          | \u2014        | posture Amber+ notified | SOP-07                |\n| Convoy > 45 min late       | ack required          | notified | \u2014                       | SOP-04 \u00a75             |\n| Urgent CASEVAC             | ack required          | \u2014        | notified                | SOP-03                |\n| Hostile-behavior air track | ack required          | notified | notify + banner         | SOP-05                |",
      },
      {
        heading: "Alternate designation",
        text: "If a primary responder (e.g., QRF) fails feasibility checks, the alternate is the nearest same-type unit with passing checks; ties break by lowest callsign. The designation is a logged operator decision.",
      },
      {
        heading: "Time standards",
        text: "Acknowledgment: 2 sim-minutes (high), 1 sim-minute (critical). Unacknowledged critical alerts re-notify every 2 sim-minutes and appear in the after-action report with total unacknowledged time.",
      },
    ],
  },
  {
    id: "SOP-01",
    category: "SOP",
    title: "Patrol Operations & Contact Reporting",
    tags: ["patrol", "reporting", "contact", "sitrep"],
    version: "1.0",
    content:
      "# SOP-01 \u2014 Patrol Operations & Contact Reporting\n\n_Simulated training document. Not real doctrine._\n\n## 1. Patrol conduct\n\nPatrol units follow their assigned patrol zone and route. Deviation greater than 500 m from the assigned zone requires operator authorization, logged as a tasking event. Patrol speed defaults to zone standard; reduced-visibility conditions (fog, storm, night without NVG allocation) mandate a speed reduction to 60% and a doubled reporting cadence.\n\n## 2. Reporting cadence\n\nRoutine position reports every 15 sim-minutes. A missed report window triggers a comms-check at +5 minutes; two consecutive missed reports escalate under SOP-06 (Comms-Loss Protocol).\n\n## 3. Contact reporting\n\nOn any contact (unidentified persons, vehicles, or activity), the unit transmits a SALUTE-format report: **S**ize, **A**ctivity, **L**ocation, **U**nit/Uniform, **T**ime, **E**quipment. Contact reports are always severity **high** or above at initial classification (see REF-02) and are downgraded only by the operator after assessment.\n\n## 4. Post-contact actions\n\nThe unit holds observation unless directly threatened, awaits operator tasking, and does not pursue. QRF dispatch decisions follow SOP-02. All contact events are preserved in the run log for after-action review under POL-03.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-01 \u2014 Patrol Operations & Contact Reporting",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Patrol conduct",
        text: "Patrol units follow their assigned patrol zone and route. Deviation greater than 500 m from the assigned zone requires operator authorization, logged as a tasking event. Patrol speed defaults to zone standard; reduced-visibility conditions (fog, storm, night without NVG allocation) mandate a speed reduction to 60% and a doubled reporting cadence.",
      },
      {
        heading: "2. Reporting cadence",
        text: "Routine position reports every 15 sim-minutes. A missed report window triggers a comms-check at +5 minutes; two consecutive missed reports escalate under SOP-06 (Comms-Loss Protocol).",
      },
      {
        heading: "3. Contact reporting",
        text: "On any contact (unidentified persons, vehicles, or activity), the unit transmits a SALUTE-format report: **S**ize, **A**ctivity, **L**ocation, **U**nit/Uniform, **T**ime, **E**quipment. Contact reports are always severity **high** or above at initial classification (see REF-02) and are downgraded only by the operator after assessment.",
      },
      {
        heading: "4. Post-contact actions",
        text: "The unit holds observation unless directly threatened, awaits operator tasking, and does not pursue. QRF dispatch decisions follow SOP-02. All contact events are preserved in the run log for after-action review under POL-03.",
      },
    ],
  },
  {
    id: "SOP-02",
    category: "SOP",
    title: "Quick Reaction Force (QRF) Dispatch",
    tags: ["qrf", "dispatch", "response", "escalation"],
    version: "1.0",
    content:
      "# SOP-02 \u2014 Quick Reaction Force (QRF) Dispatch\n\n_Simulated training document. Not real doctrine._\n\n## 1. Dispatch criteria\n\nQRF dispatch is authorized when any of the following hold: (a) a contact report of severity **high** or **critical** (REF-02); (b) a unit under SOP-06 comms-loss escalation at stage 3; (c) a perimeter alert under SOP-07 confirmed by two independent sensors.\n\n## 2. Authorization\n\nDispatch requires operator action; the system may recommend but never auto-dispatches. The dispatch decision, its timestamp, and the authorizing role are logged as decision events.\n\n## 3. Response standards\n\nQRF acknowledges tasking within 2 sim-minutes and departs within 5. Target time-on-scene is 20 sim-minutes for in-sector responses; cross-sector responses require commander notification. En-route reporting every 5 sim-minutes.\n\n## 4. Feasibility\n\nBefore dispatch, verify: fuel above 30% for the round trip, medical kit aboard for casualty-related calls, and route feasibility under current weather (see SOP-04 route rules). If the primary QRF fails feasibility checks, the escalation matrix (REF-04) designates the alternate.\n\n## 5. Stand-down\n\nQRF returns to ready state only on operator stand-down order, logged with reason.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-02 \u2014 Quick Reaction Force (QRF) Dispatch",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Dispatch criteria",
        text: "QRF dispatch is authorized when any of the following hold: (a) a contact report of severity **high** or **critical** (REF-02); (b) a unit under SOP-06 comms-loss escalation at stage 3; (c) a perimeter alert under SOP-07 confirmed by two independent sensors.",
      },
      {
        heading: "2. Authorization",
        text: "Dispatch requires operator action; the system may recommend but never auto-dispatches. The dispatch decision, its timestamp, and the authorizing role are logged as decision events.",
      },
      {
        heading: "3. Response standards",
        text: "QRF acknowledges tasking within 2 sim-minutes and departs within 5. Target time-on-scene is 20 sim-minutes for in-sector responses; cross-sector responses require commander notification. En-route reporting every 5 sim-minutes.",
      },
      {
        heading: "4. Feasibility",
        text: "Before dispatch, verify: fuel above 30% for the round trip, medical kit aboard for casualty-related calls, and route feasibility under current weather (see SOP-04 route rules). If the primary QRF fails feasibility checks, the escalation matrix (REF-04) designates the alternate.",
      },
      {
        heading: "5. Stand-down",
        text: "QRF returns to ready state only on operator stand-down order, logged with reason.",
      },
    ],
  },
  {
    id: "SOP-03",
    category: "SOP",
    title: "Casualty Evacuation (CASEVAC)",
    tags: ["casevac", "medical", "evacuation", "vitals"],
    version: "1.0",
    content:
      "# SOP-03 \u2014 Casualty Evacuation (CASEVAC)\n\n_Simulated training document. Not real doctrine._\n\n## 1. Initiation\n\nA CASEVAC request is initiated when personnel vitals cross critical thresholds (REF-02 medical bands) or a unit transmits a casualty report. The request includes: casualty count, precedence, location, and security status of the pickup site.\n\n## 2. Precedence categories\n\n- **Urgent** \u2014 evacuation within 60 sim-minutes; vitals critical.\n- **Priority** \u2014 within 4 sim-hours; vitals degraded and worsening.\n- **Routine** \u2014 within 24 sim-hours; stable.\n\n## 3. Evacuation chain\n\nCasualties move: point of injury \u2192 casualty collection point \u2192 medical facility. The dispatching operator designates the evacuation asset; UAV assets may relay but never transport. Escort requirements follow SOP-04 when the route crosses an active-threat sector.\n\n## 4. In-transit reporting\n\nThe evacuation asset reports at pickup, at each waypoint, and at handover. Vitals telemetry for the casualty is streamed where equipment allows and attached to the run log.\n\n## 5. Records\n\nEvery CASEVAC generates a timeline entry for the after-action report: request time, dispatch time, pickup time, handover time. The urgent-precedence 60-minute standard is a primary exercise KPI.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-03 \u2014 Casualty Evacuation (CASEVAC)",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Initiation",
        text: "A CASEVAC request is initiated when personnel vitals cross critical thresholds (REF-02 medical bands) or a unit transmits a casualty report. The request includes: casualty count, precedence, location, and security status of the pickup site.",
      },
      {
        heading: "2. Precedence categories",
        text: "- **Urgent** \u2014 evacuation within 60 sim-minutes; vitals critical.\n- **Priority** \u2014 within 4 sim-hours; vitals degraded and worsening.\n- **Routine** \u2014 within 24 sim-hours; stable.",
      },
      {
        heading: "3. Evacuation chain",
        text: "Casualties move: point of injury \u2192 casualty collection point \u2192 medical facility. The dispatching operator designates the evacuation asset; UAV assets may relay but never transport. Escort requirements follow SOP-04 when the route crosses an active-threat sector.",
      },
      {
        heading: "4. In-transit reporting",
        text: "The evacuation asset reports at pickup, at each waypoint, and at handover. Vitals telemetry for the casualty is streamed where equipment allows and attached to the run log.",
      },
      {
        heading: "5. Records",
        text: "Every CASEVAC generates a timeline entry for the after-action report: request time, dispatch time, pickup time, handover time. The urgent-precedence 60-minute standard is a primary exercise KPI.",
      },
    ],
  },
  {
    id: "SOP-04",
    category: "SOP",
    title: "Convoy Escort Procedures",
    tags: ["convoy", "escort", "logistics", "route"],
    version: "1.0",
    content:
      "# SOP-04 \u2014 Convoy Escort Procedures\n\n_Simulated training document. Not real doctrine._\n\n## 1. Composition\n\nA standard escorted convoy comprises a lead escort element, cargo vehicles, and a trail escort element. Convoys of more than six cargo vehicles add a middle escort. UAV overwatch is assigned when airframe availability and weather permit.\n\n## 2. Route planning\n\nRoutes are planned in the mission planner with threat zones and weather as mandatory cost layers. The optimized route is compared against the naive route; the planner must acknowledge the difference before launch. Restricted zones are never routed through, regardless of cost savings.\n\n## 3. Movement discipline\n\nConvoy speed is the slowest vehicle's standard. Spacing: 50\u2013100 m between vehicles, doubled in reduced visibility. Halt reports at every scheduled waypoint.\n\n## 4. Incident response\n\nOn obstruction or contact: the convoy halts short, reports SALUTE (SOP-01), and holds. Escorts secure the immediate area; they do not pursue. Rerouting requires operator approval. If casualties occur, SOP-03 governs.\n\n## 5. Delay thresholds\n\nA convoy more than 20 sim-minutes behind schedule reports cause; more than 45 minutes triggers an escalation-matrix review (REF-04) for QRF readiness along the remaining route.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-04 \u2014 Convoy Escort Procedures",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Composition",
        text: "A standard escorted convoy comprises a lead escort element, cargo vehicles, and a trail escort element. Convoys of more than six cargo vehicles add a middle escort. UAV overwatch is assigned when airframe availability and weather permit.",
      },
      {
        heading: "2. Route planning",
        text: "Routes are planned in the mission planner with threat zones and weather as mandatory cost layers. The optimized route is compared against the naive route; the planner must acknowledge the difference before launch. Restricted zones are never routed through, regardless of cost savings.",
      },
      {
        heading: "3. Movement discipline",
        text: "Convoy speed is the slowest vehicle's standard. Spacing: 50\u2013100 m between vehicles, doubled in reduced visibility. Halt reports at every scheduled waypoint.",
      },
      {
        heading: "4. Incident response",
        text: "On obstruction or contact: the convoy halts short, reports SALUTE (SOP-01), and holds. Escorts secure the immediate area; they do not pursue. Rerouting requires operator approval. If casualties occur, SOP-03 governs.",
      },
      {
        heading: "5. Delay thresholds",
        text: "A convoy more than 20 sim-minutes behind schedule reports cause; more than 45 minutes triggers an escalation-matrix review (REF-04) for QRF readiness along the remaining route.",
      },
    ],
  },
  {
    id: "SOP-05",
    category: "SOP",
    title: "Counter-UAS Response",
    tags: ["counter-uas", "airspace", "drone", "detection"],
    version: "1.0",
    content:
      "# SOP-05 \u2014 Counter-UAS Response\n\n_Simulated training document. Not real doctrine._\n\n## 1. Detection and classification\n\nAny unidentified air track is classified within 3 sim-minutes as: **friendly** (transponder/flight-plan match), **unknown**, or **hostile-behavior** (loitering over restricted zones, shadowing units, or repeated perimeter approaches). Vision-service detections below the confidence threshold route to human review before classification.\n\n## 2. Alerting\n\nUnknown tracks inside a monitoring zone raise severity **medium**; inside a restricted zone, **high**; hostile-behavior classification is always **critical** and notifies the commander role directly.\n\n## 3. Response ladder\n\n1. Track and record (all classifications).\n2. Ground own UAV traffic in the affected sector (unknown in restricted zone or above).\n3. Alert ground units along the track's path; sensitive activities pause.\n4. Hostile-behavior: continuous tracking priority, QRF readiness per SOP-02, and airspace-closure recommendation to the commander.\n\nThis platform simulates detection, tracking, and defensive posture only \u2014 no engagement mechanics exist.\n\n## 4. Stand-down\n\nA track that exits the operational area and does not return within 30 sim-minutes is downgraded and archived. All track histories are preserved for after-action review.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-05 \u2014 Counter-UAS Response",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Detection and classification",
        text: "Any unidentified air track is classified within 3 sim-minutes as: **friendly** (transponder/flight-plan match), **unknown**, or **hostile-behavior** (loitering over restricted zones, shadowing units, or repeated perimeter approaches). Vision-service detections below the confidence threshold route to human review before classification.",
      },
      {
        heading: "2. Alerting",
        text: "Unknown tracks inside a monitoring zone raise severity **medium**; inside a restricted zone, **high**; hostile-behavior classification is always **critical** and notifies the commander role directly.",
      },
      {
        heading: "3. Response ladder",
        text: "1. Track and record (all classifications).\n2. Ground own UAV traffic in the affected sector (unknown in restricted zone or above).\n3. Alert ground units along the track's path; sensitive activities pause.\n4. Hostile-behavior: continuous tracking priority, QRF readiness per SOP-02, and airspace-closure recommendation to the commander.\n\nThis platform simulates detection, tracking, and defensive posture only \u2014 no engagement mechanics exist.",
      },
      {
        heading: "4. Stand-down",
        text: "A track that exits the operational area and does not return within 30 sim-minutes is downgraded and archived. All track histories are preserved for after-action review.",
      },
    ],
  },
  {
    id: "SOP-06",
    category: "SOP",
    title: "Communications-Loss Protocol",
    tags: ["comms", "comms-loss", "lost-contact", "escalation"],
    version: "1.0",
    content:
      "# SOP-06 \u2014 Communications-Loss Protocol\n\n_Simulated training document. Not real doctrine._\n\n## 1. Stages\n\n- **Stage 1 (one missed report window):** automated comms-check at +5 sim-minutes. Unit marker flagged stale on the operational picture.\n- **Stage 2 (two consecutive missed windows):** severity **medium** alert; last-known position and heading published; adjacent units notified.\n- **Stage 3 (30 sim-minutes without contact):** severity **high**; QRF readiness per SOP-02; UAV re-tasking to sweep the projected route is recommended to the operator.\n- **Stage 4 (60 sim-minutes):** severity **critical**; commander notification; search plan initiated along the movement corridor.\n\n## 2. Unit-side procedure\n\nA unit that loses communications continues to its next scheduled waypoint, then holds and attempts contact every 10 sim-minutes. After 60 minutes without contact, it proceeds to the nearest designated rally point.\n\n## 3. Re-establishment\n\nOn re-contact, the unit transmits a full status report (position, personnel, resources). The comms-loss interval is reconstructed in the event log from the unit's buffered reports and flagged for the after-action review \u2014 total comms-loss minutes is a primary exercise KPI.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-06 \u2014 Communications-Loss Protocol",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Stages",
        text: "- **Stage 1 (one missed report window):** automated comms-check at +5 sim-minutes. Unit marker flagged stale on the operational picture.\n- **Stage 2 (two consecutive missed windows):** severity **medium** alert; last-known position and heading published; adjacent units notified.\n- **Stage 3 (30 sim-minutes without contact):** severity **high**; QRF readiness per SOP-02; UAV re-tasking to sweep the projected route is recommended to the operator.\n- **Stage 4 (60 sim-minutes):** severity **critical**; commander notification; search plan initiated along the movement corridor.",
      },
      {
        heading: "2. Unit-side procedure",
        text: "A unit that loses communications continues to its next scheduled waypoint, then holds and attempts contact every 10 sim-minutes. After 60 minutes without contact, it proceeds to the nearest designated rally point.",
      },
      {
        heading: "3. Re-establishment",
        text: "On re-contact, the unit transmits a full status report (position, personnel, resources). The comms-loss interval is reconstructed in the event log from the unit's buffered reports and flagged for the after-action review \u2014 total comms-loss minutes is a primary exercise KPI.",
      },
    ],
  },
  {
    id: "SOP-07",
    category: "SOP",
    title: "Base Perimeter Defense",
    tags: ["perimeter", "base", "sensors", "defense"],
    version: "1.0",
    content:
      "# SOP-07 \u2014 Base Perimeter Defense\n\n_Simulated training document. Not real doctrine._\n\n## 1. Sensor coverage\n\nThe base perimeter is divided into numbered arcs, each covered by at least two sensor types (visual, motion, or patrol observation). A single-sensor arc is a reportable coverage gap and appears on the readiness dashboard.\n\n## 2. Alert confirmation\n\nA single sensor trigger raises severity **low** and tasks the nearest camera or patrol for confirmation. Two independent sensors within 5 sim-minutes and 200 m raise **high** and constitute a confirmed perimeter event \u2014 QRF criteria under SOP-02 apply.\n\n## 3. Response postures\n\n- **Green:** routine; standard patrol rotation.\n- **Amber:** confirmed activity near perimeter; patrols shift to affected arcs; gates restrict to essential movement.\n- **Red:** confirmed breach attempt; QRF deploys; all non-essential external activity halts; commander notified.\n\nPosture changes are operator decisions, logged with reason. The system recommends; it never changes posture autonomously.\n\n## 4. Breach handling\n\nOn a confirmed breach: contain and observe, establish inner cordon, and account for all personnel via the roster. Pursuit beyond the perimeter requires commander authorization. Full sensor and decision timelines feed the after-action report.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-07 \u2014 Base Perimeter Defense",
        text: "_Simulated training document. Not real doctrine._",
      },
      {
        heading: "1. Sensor coverage",
        text: "The base perimeter is divided into numbered arcs, each covered by at least two sensor types (visual, motion, or patrol observation). A single-sensor arc is a reportable coverage gap and appears on the readiness dashboard.",
      },
      {
        heading: "2. Alert confirmation",
        text: "A single sensor trigger raises severity **low** and tasks the nearest camera or patrol for confirmation. Two independent sensors within 5 sim-minutes and 200 m raise **high** and constitute a confirmed perimeter event \u2014 QRF criteria under SOP-02 apply.",
      },
      {
        heading: "3. Response postures",
        text: "- **Green:** routine; standard patrol rotation.\n- **Amber:** confirmed activity near perimeter; patrols shift to affected arcs; gates restrict to essential movement.\n- **Red:** confirmed breach attempt; QRF deploys; all non-essential external activity halts; commander notified.\n\nPosture changes are operator decisions, logged with reason. The system recommends; it never changes posture autonomously.",
      },
      {
        heading: "4. Breach handling",
        text: "On a confirmed breach: contain and observe, establish inner cordon, and account for all personnel via the roster. Pursuit beyond the perimeter requires commander authorization. Full sensor and decision timelines feed the after-action report.",
      },
    ],
  },
  {
    id: "SOP-08",
    category: "SOP",
    title: "HADR Deployment (Humanitarian Assistance & Disaster Relief)",
    tags: ["hadr", "relief", "deployment", "logistics"],
    version: "1.0",
    content:
      "# SOP-08 \u2014 HADR Deployment\n\n_Simulated training document. Not real doctrine._\n\nHADR is a military mission class: the same units, logistics chains, and command procedures as other operations, applied to disaster response (see scenario SC-8).\n\n## 1. Activation\n\nHADR deployment activates on tasking from the exercise authority. Initial actions: designate the operational area, establish the supply chain, and assign sector responsibilities within 60 sim-minutes of activation.\n\n## 2. Priorities\n\nFixed order unless the commander overrides with logged reason: (1) life-saving movement and medical response (SOP-03 applies unchanged), (2) route clearance for relief movement, (3) supply distribution, (4) infrastructure assessment reporting.\n\n## 3. Logistics tempo\n\nHADR consumes supplies faster than sustainment operations: rations and medical stock are re-forecast every 2 sim-hours, and the resupply threshold rises from 30% to 50% stock. Convoy movements follow SOP-04 with weather as the dominant route cost.\n\n## 4. Coordination and reporting\n\nCivilian-agency liaison is represented as report events only \u2014 no civilian units are simulated under command. Situation reports follow the standard cadence at doubled frequency during the first 12 sim-hours. All KPIs (response time, supply coverage, medical timelines) feed the after-action report and the Ch. 14 benchmark comparisons.",
    sections: [
      {
        heading: "Overview",
        text: "",
      },
      {
        heading: "SOP-08 \u2014 HADR Deployment",
        text: "_Simulated training document. Not real doctrine._\n\nHADR is a military mission class: the same units, logistics chains, and command procedures as other operations, applied to disaster response (see scenario SC-8).",
      },
      {
        heading: "1. Activation",
        text: "HADR deployment activates on tasking from the exercise authority. Initial actions: designate the operational area, establish the supply chain, and assign sector responsibilities within 60 sim-minutes of activation.",
      },
      {
        heading: "2. Priorities",
        text: "Fixed order unless the commander overrides with logged reason: (1) life-saving movement and medical response (SOP-03 applies unchanged), (2) route clearance for relief movement, (3) supply distribution, (4) infrastructure assessment reporting.",
      },
      {
        heading: "3. Logistics tempo",
        text: "HADR consumes supplies faster than sustainment operations: rations and medical stock are re-forecast every 2 sim-hours, and the resupply threshold rises from 30% to 50% stock. Convoy movements follow SOP-04 with weather as the dominant route cost.",
      },
      {
        heading: "4. Coordination and reporting",
        text: "Civilian-agency liaison is represented as report events only \u2014 no civilian units are simulated under command. Situation reports follow the standard cadence at doubled frequency during the first 12 sim-hours. All KPIs (response time, supply coverage, medical timelines) feed the after-action report and the Ch. 14 benchmark comparisons.",
      },
    ],
  },
];
