/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RunRouteImport } from './routes/run'
import { Route as ScenarioEditorRouteImport } from './routes/scenario-editor'
import { Route as SitrepRouteImport } from './routes/sitrep'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as WarroomRouteImport } from './routes/warroom'
import { Route as WhatifRouteImport } from './routes/whatif'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioEditorRoute = ScenarioEditorRouteImport.update({
  id: '/scenario-editor',
  path: '/scenario-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitrepRoute = SitrepRouteImport.update({
  id: '/sitrep',
  path: '/sitrep',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const WarroomRoute = WarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/doctrine': typeof DoctrineRoute
  '/logistics': typeof LogisticsRoute
  '/personnel': typeof PersonnelRoute
  '/planner': typeof PlannerRoute
  '/replay': typeof ReplayRoute
  '/run': typeof RunRoute
  '/scenario-editor': typeof ScenarioEditorRoute
  '/sitrep': typeof SitrepRoute
  '/vision': typeof VisionRoute
  '/warroom': typeof WarroomRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/doctrine': typeof DoctrineRoute
  '/logistics': typeof LogisticsRoute
  '/personnel': typeof PersonnelRoute
  '/planner': typeof PlannerRoute
  '/replay': typeof ReplayRoute
  '/run': typeof RunRoute
  '/scenario-editor': typeof ScenarioEditorRoute
  '/sitrep': typeof SitrepRoute
  '/vision': typeof VisionRoute
  '/warroom': typeof WarroomRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/doctrine': typeof DoctrineRoute
  '/logistics': typeof LogisticsRoute
  '/personnel': typeof PersonnelRoute
  '/planner': typeof PlannerRoute
  '/replay': typeof ReplayRoute
  '/run': typeof RunRoute
  '/scenario-editor': typeof ScenarioEditorRoute
  '/sitrep': typeof SitrepRoute
  '/vision': typeof VisionRoute
  '/warroom': typeof WarroomRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/dashboard'
    | '/doctrine'
    | '/logistics'
    | '/personnel'
    | '/planner'
    | '/replay'
    | '/run'
    | '/scenario-editor'
    | '/sitrep'
    | '/vision'
    | '/warroom'
    | '/whatif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/dashboard'
    | '/doctrine'
    | '/logistics'
    | '/personnel'
    | '/planner'
    | '/replay'
    | '/run'
    | '/scenario-editor'
    | '/sitrep'
    | '/vision'
    | '/warroom'
    | '/whatif'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/analytics'
    | '/dashboard'
    | '/doctrine'
    | '/logistics'
    | '/personnel'
    | '/planner'
    | '/replay'
    | '/run'
    | '/scenario-editor'
    | '/sitrep'
    | '/vision'
    | '/warroom'
    | '/whatif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DoctrineRoute: typeof DoctrineRoute
  LogisticsRoute: typeof LogisticsRoute
  PersonnelRoute: typeof PersonnelRoute
  PlannerRoute: typeof PlannerRoute
  ReplayRoute: typeof ReplayRoute
  RunRoute: typeof RunRoute
  ScenarioEditorRoute: typeof ScenarioEditorRoute
  SitrepRoute: typeof SitrepRoute
  VisionRoute: typeof VisionRoute
  WarroomRoute: typeof WarroomRoute
  WhatifRoute: typeof WhatifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-editor': {
      id: '/scenario-editor'
      path: '/scenario-editor'
      fullPath: '/scenario-editor'
      preLoaderRoute: typeof ScenarioEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitrep': {
      id: '/sitrep'
      path: '/sitrep'
      fullPath: '/sitrep'
      preLoaderRoute: typeof SitrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warroom': {
      id: '/warroom'
      path: '/warroom'
      fullPath: '/warroom'
      preLoaderRoute: typeof WarroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DoctrineRoute: DoctrineRoute,
  LogisticsRoute: LogisticsRoute,
  PersonnelRoute: PersonnelRoute,
  PlannerRoute: PlannerRoute,
  ReplayRoute: ReplayRoute,
  RunRoute: RunRoute,
  ScenarioEditorRoute: ScenarioEditorRoute,
  SitrepRoute: SitrepRoute,
  VisionRoute: VisionRoute,
  WarroomRoute: WarroomRoute,
  WhatifRoute: WhatifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
